import type { CrmUserRole } from '@prisma/client';

export const CRM_MODULES = [
  'dashboard',
  'mission_control',
  'command_center',
  'analytics',
  'sales_pipeline',
  'clients',
  'leads',
  'followups',
  'quotes',
  'bookings',
  'escrow',
  'refunds',
  'invoices',
  'packages',
  'themes',
  'catalog',
  'stays',
  'cars',
  'locations',
  'assets',
  'visual_ai',
  'vendors',
  'approvals',
  'promotions',
  'banners',
  'promo_codes',
  'eventhub_cms',
  'permit_cms',
  'campaigns',
  'automations',
  'audiences',
  'seo',
  'careers',
  'email_templates',
  'users',
  'security_center',
] as const;

const broad = [...CRM_MODULES];
export const DEFAULT_ROLE_PERMISSIONS: Record<CrmUserRole, readonly string[]> = {
  admin: broad,
  manager: broad,
  editor: broad.filter((key) => !['seo', 'users', 'security_center'].includes(key)),
  approver: [
    'mission_control',
    'dashboard',
    'command_center',
    'vendors',
    'approvals',
    'escrow',
    'refunds',
    'invoices',
  ],
  sales: [
    'dashboard',
    'command_center',
    'sales_pipeline',
    'clients',
    'leads',
    'followups',
    'quotes',
    'bookings',
    'locations',
  ],
  support: [
    'dashboard',
    'command_center',
    'clients',
    'leads',
    'followups',
    'bookings',
    'escrow',
    'refunds',
    'invoices',
  ],
  finance: [
    'dashboard',
    'command_center',
    'quotes',
    'bookings',
    'escrow',
    'refunds',
    'invoices',
    'vendors',
    'approvals',
  ],
  marketing: [
    'dashboard',
    'promotions',
    'banners',
    'promo_codes',
    'eventhub_cms',
    'permit_cms',
    'campaigns',
    'automations',
    'audiences',
    'email_templates',
    'clients',
  ],
  operations: [
    'dashboard',
    'packages',
    'themes',
    'catalog',
    'stays',
    'cars',
    'assets',
    'locations',
    'vendors',
    'approvals',
  ],
  viewer: ['dashboard', 'command_center', 'clients', 'locations'],
};
