import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const checkedAt = new Date('2026-08-20T00:00:00.000Z');

type RegionalVendor = {
  slug: string;
  name: string;
  categories: Array<'venue' | 'photography' | 'catering' | 'decoration' | 'organizer'>;
  coverage: string[];
  address: string;
  phone: string | null;
  email: string | null;
  website: string;
  source: string;
  bio: string;
};

const vendors: RegionalVendor[] = [
  {
    slug: 'novotel-hyderabad-convention-centre',
    name: 'Novotel Hyderabad Convention Centre & HICC',
    categories: ['venue'],
    coverage: ['Hyderabad', 'Telangana'],
    address: 'Novotel & HICC Complex, adjacent to HITEC City, Cyberabad Post Office, Hyderabad, Telangana 500081',
    phone: '+91 40 6606 7000',
    email: 'H6182-re@accor.com',
    website: 'https://www.novotelhyderabad.com/meetings-events/weddings-special-events/',
    source: 'https://www.novotelhyderabad.com/meetings-events/weddings-special-events/',
    bio: 'Large-format convention, wedding and social-event venue complex with indoor and outdoor spaces and on-site catering.',
  },
  {
    slug: 'eventara-convention-centre',
    name: 'Eventara Convention Centre',
    categories: ['venue'],
    coverage: ['Hyderabad', 'Telangana'],
    address: 'Door No. 3-99/1, Vattinagulapally, Gandipet, Hyderabad, Telangana 500075',
    phone: '+91 96597 28728',
    email: null,
    website: 'https://www.eventara.vip/',
    source: 'https://www.eventara.vip/contact/',
    bio: 'Convention and wedding venue in Hyderabad Financial District with large hall and lawn configurations.',
  },
  {
    slug: 'esci-centenary-convention-center',
    name: 'ESCI Centenary Convention Center',
    categories: ['venue'],
    coverage: ['Hyderabad', 'Telangana'],
    address: 'ESCI Road, beside Khajaguda Lake, Gate No. 1, Gachibowli, Hyderabad, Telangana 500032',
    phone: '+91 97401 01005',
    email: 'esciccc@escihyd.org',
    website: 'https://www.esciconvention.org/',
    source: 'https://www.esciconvention.org/facility',
    bio: 'Convention facility with exhibition, auditorium, seminar, dining and open-air event spaces.',
  },
  {
    slug: 'the-celeste-hyderabad',
    name: 'The Celeste',
    categories: ['venue'],
    coverage: ['Hyderabad', 'Rangareddy', 'Telangana'],
    address: 'Saffron Holidays and Resorts, Survey No. 203, Tummaloor, Rangareddy, Telangana 501359',
    phone: '+91 77669 99123',
    email: 'info@theceleste.co.in',
    website: 'https://theceleste.co.in/',
    source: 'https://theceleste.co.in/contactus',
    bio: 'Convention centre and wedding-lawns property serving celebrations and large social events.',
  },
  {
    slug: 'svl-arena',
    name: 'SVL Arena Convention Centre',
    categories: ['venue'],
    coverage: ['Hyderabad', 'Telangana'],
    address: 'Rockhills Colony, L.B. Nagar, Hyderabad, Telangana 500068',
    phone: '+91 70754 49962',
    email: 'svlarena234@gmail.com',
    website: 'https://svlarena.com/',
    source: 'https://svlarena.com/about-us.php',
    bio: 'Wedding, conference and event venue with multiple spaces, lawns and capacity for large gatherings.',
  },
  {
    slug: 'naina-conventions',
    name: 'Naina Conventions',
    categories: ['venue'],
    coverage: ['Hyderabad', 'Telangana'],
    address: 'Kukatpally Y Junction, near Metro Pillar No. 850, Hyderabad, Telangana',
    phone: '+91 80960 09919',
    email: 'bookings@nainaconventions.com',
    website: 'https://www.nainaconventions.com/',
    source: 'https://www.nainaconventions.com/',
    bio: 'Purpose-built Hyderabad venue for weddings, corporate events, social gatherings and exhibitions.',
  },
  {
    slug: 'sree-seetharama-gardens',
    name: 'Sree SeethaRama Gardens AC Convention Centre',
    categories: ['venue'],
    coverage: ['Vijayawada', 'Andhra Pradesh'],
    address: 'D.No. 5-62, Vijayawada-Machilipatnam Road, Edupugallu, Vijayawada, Andhra Pradesh 521151',
    phone: '+91 99850 11966',
    email: 'info@ssrgardens.com',
    website: 'https://www.ssrgardens.com/',
    source: 'https://www.ssrgardens.com/',
    bio: 'Air-conditioned wedding and function venue with dining halls, an open-air stage and large parking areas.',
  },
  {
    slug: 'sai-jewel-convention-center',
    name: 'Sai Jewel Convention Center',
    categories: ['venue'],
    coverage: ['Vijayawada', 'Andhra Pradesh'],
    address: 'Teachers Colony, Road No. 1, Saibaba Temple Road, Vijayawada, Andhra Pradesh 520008',
    phone: '+91 92486 66660',
    email: 'info@saijewel.com',
    website: 'https://www.saijewel.com/',
    source: 'https://www.saijewel.com/',
    bio: 'Multi-space convention centre for weddings, conferences, exhibitions and social events.',
  },
  {
    slug: 'shore-view-events',
    name: 'Group Shore View',
    categories: ['venue', 'catering'],
    coverage: ['Vijayawada', 'Andhra Pradesh'],
    address: 'D.No. 40-17-1&2, Pitchaiah Street, Dr. V. Rao Hospital Road, Labbipet, Vijayawada, Andhra Pradesh 520010',
    phone: '+91 80082 11986',
    email: 'sharan@shoreview.in',
    website: 'https://www.shoreview.in/',
    source: 'https://www.shoreview.in/contact',
    bio: 'Vijayawada group operating convention centres, wedding halls, banquet halls and outdoor catering.',
  },
  {
    slug: 'amaravathi-conventions-vijayawada',
    name: 'Amaravathi Conventions',
    categories: ['venue'],
    coverage: ['Vijayawada', 'Andhra Pradesh'],
    address: 'Above Vijaya Krishna Super Bazar, Bunder Road, Vijayawada, Andhra Pradesh 520002',
    phone: '+91 90003 87878',
    email: 'amaravathiconventions@gmail.com',
    website: 'https://www.amaravaticonventions.in/',
    source: 'https://www.amaravaticonventions.in/',
    bio: 'City-centre venue for weddings, receptions, corporate programmes and private celebrations.',
  },
  {
    slug: 'ayurvan-resort-convention',
    name: 'Ayurvan Resort & Convention',
    categories: ['venue'],
    coverage: ['Vijayawada', 'Andhra Pradesh'],
    address: 'Vikas College Road, beside Polavaram Canal, Nunna, Vijayawada, NTR District, Andhra Pradesh 521212',
    phone: '+91 93915 89999',
    email: 'info@ayurvanresort.com',
    website: 'https://www.ayurvanresort.com/',
    source: 'https://www.ayurvanresort.com/convention.php',
    bio: 'Resort convention venue with an air-conditioned hall and landscaped event lawn.',
  },
  {
    slug: 'pixel-army-hyderabad',
    name: 'Pixel Army',
    categories: ['photography'],
    coverage: ['Hyderabad', 'Telangana'],
    address: 'Prashasan Nagar, Jubilee Hills, Hyderabad, Telangana 500096',
    phone: '+91 97047 05507',
    email: 'hello@pixelarmy.studio',
    website: 'https://www.pixelarmy.studio/',
    source: 'https://pixelarmy.pixieset.com/',
    bio: 'Hyderabad wedding photography and filmmaking studio covering engagements, weddings and couple shoots.',
  },
  {
    slug: 'the-pixel-shot-hyderabad',
    name: 'ThePixelShot Photography & Films',
    categories: ['photography'],
    coverage: ['Hyderabad', 'Telangana'],
    address: 'Hyderabad, Telangana',
    phone: '+91 80975 53546',
    email: 'thepixelshot.in@gmail.com',
    website: 'https://www.thepixelshot.in/',
    source: 'https://www.thepixelshot.in/About-Us',
    bio: 'Wedding photography and films for pre-weddings, haldi ceremonies, weddings and related events.',
  },
  {
    slug: 'ranga-surya-photography',
    name: 'Ranga Surya Photography',
    categories: ['photography'],
    coverage: ['Hyderabad', 'Telangana', 'Vijayawada', 'Visakhapatnam', 'Rajahmundry', 'Bhimavaram', 'Andhra Pradesh'],
    address: '100 Feet Road, Enikepadu, Vijayawada, Andhra Pradesh 521108',
    phone: '+91 99598 90543',
    email: 'rangasuryaphotography@gmail.com',
    website: 'https://www.rangasuryaphotography.com/',
    source: 'https://www.rangasuryaphotography.com/',
    bio: 'Wedding, candid and pre-wedding photography studio with branches across Telangana and Andhra Pradesh.',
  },
  {
    slug: 'bisi-bisi-catering',
    name: 'Bisi Bisi Catering',
    categories: ['catering'],
    coverage: ['Hyderabad', 'Telangana'],
    address: 'Aarka Prime, Plot No. 797, Road No. 36, Jubilee Hills, Hyderabad, Telangana 500033',
    phone: '+91 90329 87111',
    email: 'catering@bisibisi.in',
    website: 'https://bisibisi.com/catering',
    source: 'https://bisibisi.com/contact',
    bio: 'Andhra, Telangana and Karnataka cuisine catering for ceremonies, weddings, corporate events and family functions.',
  },
  {
    slug: 'jyothi-caterers-hyderabad',
    name: 'Jyothi Caterers',
    categories: ['catering'],
    coverage: ['Hyderabad', 'Telangana'],
    address: 'Near Srinivasa Nagar, Boduppal, Uppal, Hyderabad, Telangana 500092',
    phone: '+91 92966 59876',
    email: 'info@jyothicaterers.in',
    website: 'https://jyothicaterers.com/',
    source: 'https://jyothicaterers.com/contact-us/',
    bio: 'Wedding and event caterer offering menu planning and service across Hyderabad.',
  },
  {
    slug: 'chandan-caterers-hyderabad',
    name: 'Chandan Caterers',
    categories: ['catering'],
    coverage: ['Hyderabad', 'Secunderabad', 'Telangana'],
    address: 'H.No. 12-11-698, Warasiguda, Secunderabad, Telangana 500061',
    phone: '+91 98484 69393',
    email: 'chandan.caterers@gmail.com',
    website: 'https://www.chandancaterers.in/',
    source: 'https://www.chandancaterers.in/contact.html',
    bio: 'Food catering and hospitality for weddings, conferences, birthdays and launch events.',
  },
  {
    slug: 'sree-foods-catering-hyderabad',
    name: 'Sree Foods Catering',
    categories: ['catering'],
    coverage: ['Hyderabad', 'Telangana'],
    address: 'Flat 102/A, Jubilee Homes Apartment, Road No. 2, Indra Nagar, Kothapet, Hyderabad, Telangana 500035',
    phone: '+91 99129 26962',
    email: 'sreefoods.23@gmail.com',
    website: 'https://www.sreefoodscatering.com/',
    source: 'https://www.sreefoodscatering.com/',
    bio: 'Hyderabad caterer for weddings, birthdays, house functions and farmhouse events.',
  },
  {
    slug: 'amrutham-padma-catering',
    name: 'Amrutham by Padma Catering',
    categories: ['catering'],
    coverage: ['Visakhapatnam', 'Vizag', 'Andhra Pradesh'],
    address: 'MVP Sector 8, Visakhapatnam, Andhra Pradesh',
    phone: '+91 86866 22722',
    email: null,
    website: 'https://padmacatering.com/',
    source: 'https://padmacatering.com/',
    bio: 'Visakhapatnam wedding and event catering company operating since 1993.',
  },
  {
    slug: 'pragnya-caterers-vijayawada',
    name: 'Pragnya Caterers',
    categories: ['catering'],
    coverage: ['Vijayawada', 'Andhra Pradesh'],
    address: 'Gurunanak Colony Main Road, Vijayawada, Andhra Pradesh',
    phone: '+91 99882 21558',
    email: 'pragnyacaterers@gmail.com',
    website: 'https://pragnyacaterers.com/',
    source: 'https://pragnyacaterers.com/',
    bio: 'Vijayawada catering for weddings, receptions, corporate events and family functions.',
  },
  {
    slug: 'sharma-events-caterers',
    name: 'Sharma Events & Caterers',
    categories: ['catering', 'decoration', 'organizer'],
    coverage: ['Hyderabad', 'Secunderabad', 'Telangana'],
    address: 'Sainik Vihar Road No. 1, Kakatiya Nagar, A.S. Rao Nagar, Secunderabad, Telangana 500056',
    phone: '+91 93910 40987',
    email: 'sharmaeventsandcaterers@gmail.com',
    website: 'https://www.sharmaeventsandcaterers.in/',
    source: 'https://www.sharmaeventsandcaterers.in/',
    bio: 'Hyderabad event design, decoration, planning and catering business.',
  },
  {
    slug: 'thoranam-events',
    name: 'Thoranam Events',
    categories: ['decoration', 'organizer'],
    coverage: ['Hyderabad', 'Secunderabad', 'Telangana'],
    address: 'Saket Road, ECIL, Hyderabad, Telangana 500062',
    phone: '+91 78426 42495',
    email: null,
    website: 'https://www.thoranam.com/',
    source: 'https://www.thoranam.com/',
    bio: 'Wedding-stage, birthday, cradle-ceremony, haldi, engagement and corporate-event decoration across Hyderabad.',
  },
  {
    slug: 'lalitha-event-decors',
    name: 'Lalitha Event Decors',
    categories: ['decoration'],
    coverage: ['Visakhapatnam', 'Vizag', 'Andhra Pradesh'],
    address: '10-9-5, High School Road, Gajuwaka, Visakhapatnam, Andhra Pradesh 530026',
    phone: '+91 86866 12186',
    email: 'lalithaeventdecors@gmail.com',
    website: 'https://www.lalithaeventdecors.com/',
    source: 'https://www.lalithaeventdecors.com/contact',
    bio: 'Visakhapatnam event-decoration supplier for weddings and celebrations.',
  },
  {
    slug: 'siree-events-vijayawada',
    name: 'Siree Events',
    categories: ['decoration', 'organizer'],
    coverage: ['Vijayawada', 'Andhra Pradesh'],
    address: 'Vijayawada, Andhra Pradesh',
    phone: '+91 96662 04467',
    email: 'sireedecors@gmail.com',
    website: 'https://sireeevents.com/',
    source: 'https://sireeevents.com/',
    bio: 'Vijayawada wedding, floral, stage, traditional-function and corporate-event decoration.',
  },
  {
    slug: 'mahima-events-vijayawada',
    name: 'Mahima Events',
    categories: ['decoration', 'organizer'],
    coverage: ['Vijayawada', 'Andhra Pradesh'],
    address: '56-6-18/2, Maruthi Nagar, Patamata, Vijayawada, Andhra Pradesh 520010',
    phone: '+91 83743 13249',
    email: 'mahimaballoondecorations@gmail.com',
    website: 'https://mahimaevents.in/',
    source: 'https://mahimaevents.in/',
    bio: 'Vijayawada event styling and decoration for weddings, traditional ceremonies, birthdays and corporate events.',
  },
  {
    slug: 'vedam-events-vijayawada',
    name: 'Vedam Events',
    categories: ['decoration', 'organizer'],
    coverage: ['Vijayawada', 'Andhra Pradesh'],
    address: 'Vijayawada, Andhra Pradesh',
    phone: '+91 99662 23989',
    email: 'vedamteja@gmail.com',
    website: 'https://vedamevents.com/',
    source: 'https://vedamevents.com/Contactus.html',
    bio: 'Vijayawada event planning, coordination, decoration and execution business.',
  },
];

async function main() {
  for (const vendor of vendors) {
    const data = {
      company_name: vendor.name,
      contact_name: 'Bookings Team',
      email: vendor.email,
      phone: vendor.phone,
      whatsapp: vendor.phone,
      service_categories: JSON.stringify(vendor.categories),
      coverage_areas: JSON.stringify(vendor.coverage),
      address: vendor.address,
      website_url: vendor.website,
      bio: vendor.bio,
      image_key: 'regional-vendor',
      status: 'approved' as const,
      approved_by: 'official-site-research',
      approved_at: checkedAt,
      is_verified: true,
      source_name: 'Official business website',
      contact_source_url: vendor.source,
      google_search_url: `https://www.google.com/search?q=${encodeURIComponent(`${vendor.name} ${vendor.address}`)}`,
      last_checked_at: checkedAt,
      confidence: 'verified',
      research_notes: 'Contact details were published by the business on its website. Inclusion is a regional directory record, not a ranking endorsement.',
    };

    await prisma.vendors.upsert({
      where: { slug: vendor.slug },
      update: data,
      create: { slug: vendor.slug, ...data },
    });
  }

  console.info(`Seeded ${vendors.length} sourced Telangana and Andhra Pradesh vendors.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
